/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_woolensheep_emojiedit_Search */

#ifndef _Included_top_woolensheep_emojiedit_Search
#define _Included_top_woolensheep_emojiedit_Search
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_woolensheep_emojiedit_Search
 * Method:    jniSearch
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_woolensheep_emojiedit_Search_jniSearch
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
